version: '3.8'

services:
  # 1. Base de Datos
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - waiwa-net

  # 2. Backend API
  backend:
    build: ./backend/plataforma_backend
    restart: always
    environment:
      PORT: 3001
      HOST: '0.0.0.0'
      DATABASE_URL: postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      JWT_SECRET: ${JWT_SECRET}
      PG_USER: ${DB_USER}
      PG_PASSWORD: ${DB_PASSWORD}
      PG_DATABASE: ${DB_NAME}
      PG_PORT: ${PG_PORT}
      PG_HOST: ${PG_HOST}
    ports:
      - "3001:3001"
    depends_on:
      - db
    networks:
      - waiwa-net

  # 3. Frontend Principal
  frontend:
    build: ./frontend/plataforma_frontend
    restart: always
    environment:
      INTERNAL_API_URL: http://backend:3001
      NEXT_PUBLIC_API_URL: http://localhost/api
      API_URL: http://backend:3001
      NEXT_PUBLIC_FORM_URL: http://formulario:3002
    networks:
      - waiwa-net

  # 4. Frontend Formulario
  formulario:
    build: ./frontend-formulario/formulario
    restart: always
    ports:
      - "3002:3002"
    environment:
      NEXT_PUBLIC_API_URL: http://backend:3001
    networks:
      - waiwa-net

  # 5. Nginx (Proxy Inverso)
  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      # - "443:443" # Descomentar cuando configures SSL
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - backend
      - frontend
      - formulario
    networks:
      - waiwa-net

volumes:
  db_data:


networks:
  waiwa-net:
