name: Deploy to Production

on:
  push:
    branches:
      - main  # Se ejecuta al hacer push/merge a main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar repositorio
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Conectar por SSH al servidor
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/waiwahost           # Ruta de tu proyecto en el servidor
            git reset --hard                 # Asegura que no haya cambios locales que bloqueen git pull
            git pull origin main
            docker compose build frontend backend formulario
            docker compose up -d
            docker restart $(docker ps -q)
